"""alter db

Revision ID: 0dde2b383d6b
Revises: None
Create Date: 2016-06-20 14:22:49.253435

"""

# revision identifiers, used by Alembic.
revision = '0dde2b383d6b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
