"""alter db

Revision ID: 1107401a9ac6
Revises: 5a3c381faf97
Create Date: 2014-08-16 20:53:58.410137

"""

# revision identifiers, used by Alembic.
revision = '1107401a9ac6'
down_revision = '5a3c381faf97'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('name', sa.String(length=64), nullable=False))
    op.create_unique_constraint('unique_idx_name_supplier', 'supplier', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_idx_name_supplier', 'supplier')
    op.drop_column('supplier', 'name')
    ### end Alembic commands ###
