"""alter db

Revision ID: 12645ce26efd
Revises: None
Create Date: 2015-03-09 18:45:24.766585

"""

# revision identifiers, used by Alembic.
revision = '12645ce26efd'
down_revision = None

from alembic import op
import sqlalchemy as sa
from travelcrm.lib import EnumIntType
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.add_column('employee_notification', sa.Column('status', EnumIntType(), nullable=True))
    op.drop_column('task', 'closed')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('closed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('employee_notification', 'status')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    ### end Alembic commands ###
