"""alter db

Revision ID: 14346fefb145
Revises: 3714a2ddadd2
Create Date: 2014-10-20 22:30:28.852566

"""

# revision identifiers, used by Alembic.
revision = '14346fefb145'
down_revision = '3714a2ddadd2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('service_item_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], name='fk_currency_id_service_item', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name='fk_resource_id_calculation', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['service_item_id'], ['service_item.id'], name='fk_service_item_id_caluclation', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculation')
    ### end Alembic commands ###
