"""alter db

Revision ID: 1554dfca202a
Revises: 5e7cd4ddaa5
Create Date: 2014-09-07 16:59:58.819204

"""

# revision identifiers, used by Alembic.
revision = '1554dfca202a'
down_revision = '5e7cd4ddaa5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liability_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('liability_id', sa.Integer(), nullable=False),
    sa.Column('touroperator_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], name='fk_currency_id_liability_item', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['liability_id'], ['liability.id'], name='fk_liability_id_liability_item', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name='fk_resource_id_liability_item', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['touroperator_id'], ['touroperator.id'], name='fk_touroperator_id_liability_item', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liability_item')
    ### end Alembic commands ###
