"""alter db

Revision ID: 15d60ce5de5d
Revises: 42dc01faf677
Create Date: 2015-03-07 18:53:07.403490

"""

# revision identifiers, used by Alembic.
revision = '15d60ce5de5d'
down_revision = '42dc01faf677'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.add_column('task', sa.Column('status', travelcrm.lib.EnumIntType(), nullable=True))
    op.drop_column('task', 'closed')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('closed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('task', 'status')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    ### end Alembic commands ###
