"""alter db

Revision ID: 15e6f8d3ab2c
Revises: None
Create Date: 2015-01-07 12:02:43.237732

"""

# revision identifiers, used by Alembic.
revision = '15e6f8d3ab2c'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.add_column('navigation', sa.Column('action', sa.String(length=32), nullable=True))
    op.add_column('structure', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_structure_company_id', 'structure', 'company', ['company_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_structure_company_id', 'structure', type_='foreignkey')
    op.drop_column('structure', 'company_id')
    op.drop_column('navigation', 'action')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    ### end Alembic commands ###
