"""alter db

Revision ID: 161687c38a49
Revises: 265684c8e5c4
Create Date: 2015-04-24 22:04:55.013765

"""

# revision identifiers, used by Alembic.
revision = '161687c38a49'
down_revision = '265684c8e5c4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.create_unique_constraint('unique_idx_accomodation_name', 'accomodation', ['name'])
    op.drop_constraint(u'unique_idx_accomodation_type_name', 'accomodation', type_='unique')
    op.add_column('tour_sale_point', sa.Column('accomodation_id', sa.Integer(), nullable=True))
    op.add_column('tour_sale_point', sa.Column('descr', sa.String(length=255), nullable=True))
    op.drop_constraint(u'fk_accomodation_id_tour_point', 'tour_sale_point', type_='foreignkey')
    op.create_foreign_key('fk_accomodation_id_tour_sale_point', 'tour_sale_point', 'accomodation', ['accomodation_id'], ['id'])
    op.drop_column('tour_sale_point', 'accomodation_type_id')
    op.drop_column('tour_sale_point', 'description')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_sale_point', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tour_sale_point', sa.Column('accomodation_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_accomodation_id_tour_sale_point', 'tour_sale_point', type_='foreignkey')
    op.create_foreign_key(u'fk_accomodation_id_tour_point', 'tour_sale_point', 'accomodation', ['accomodation_type_id'], ['id'])
    op.drop_column('tour_sale_point', 'descr')
    op.drop_column('tour_sale_point', 'accomodation_id')
    op.create_unique_constraint(u'unique_idx_accomodation_type_name', 'accomodation', ['name'])
    op.drop_constraint('unique_idx_accomodation_name', 'accomodation', type_='unique')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    ### end Alembic commands ###
