"""alter db

Revision ID: 16963b42ef74
Revises: 3ef04f81797a
Create Date: 2014-04-28 14:16:26.448451

"""

# revision identifiers, used by Alembic.
revision = '16963b42ef74'
down_revision = '3ef04f81797a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment_row')
    op.add_column('appointment', sa.Column('date', sa.Date(), nullable=True))
    op.drop_column('appointment', 'appointment_date')
    op.alter_column('appointment', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointment', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointment', 'position_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointment', 'salary',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment', 'salary',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=True)
    op.alter_column('appointment', 'position_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointment', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointment', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('appointment', sa.Column('appointment_date', sa.DATE(), nullable=True))
    op.drop_column('appointment', 'date')
    op.create_table('appointment_row',
    sa.Column('id', sa.INTEGER(), server_default="nextval('employees_appointments_r_id_seq'::regclass)", nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], [u'appointment.id'], name=u'fk_appointment_id_appointment_row', onupdate=u'CASCADE', ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], [u'employee.id'], name=u'fk_employee_id_appointment_row', onupdate=u'CASCADE', ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], [u'position.id'], name=u'fk_position_id_appointment_row', onupdate=u'CASCADE', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id', name=u'appointment_row_pk')
    )
    ### end Alembic commands ###
