"""alter db

Revision ID: 177212a68a4a
Revises: 49ad83cca5d7
Create Date: 2015-07-22 12:52:20.189351

"""

# revision identifiers, used by Alembic.
revision = '177212a68a4a'
down_revision = '49ad83cca5d7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passport_upload',
    sa.Column('passport_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['passport_id'], ['passport.id'], name='fk_passport_id_passport_upload', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload.id'], name='fk_upload_id_passport_upload', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('passport_id', 'upload_id')
    )
    op.drop_table('apscheduler_jobs')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    op.drop_table('passport_upload')
    ### end Alembic commands ###
