"""alter db

Revision ID: 18106941cc0d
Revises: 1cb89aca614a
Create Date: 2014-05-17 13:11:06.587136

"""

# revision identifiers, used by Alembic.
revision = '18106941cc0d'
down_revision = '1cb89aca614a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
