"""alter db

Revision ID: 18572a9133a9
Revises: 41d144e9292d
Create Date: 2015-03-15 17:15:18.174409

"""

# revision identifiers, used by Alembic.
revision = '18572a9133a9'
down_revision = '41d144e9292d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.alter_column('contact', 'contact_type',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('contact', 'contact_type_1')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('contact_type_1', postgresql.ENUM(u'phone', u'email', u'skype', name='contact_type_enum'), autoincrement=False, nullable=False))
    op.alter_column('contact', 'contact_type',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    ### end Alembic commands ###
