"""alter db

Revision ID: 18edfb87777e
Revises: 40316bc3ca16
Create Date: 2014-10-01 21:54:46.038064

"""

# revision identifiers, used by Alembic.
revision = '18edfb87777e'
down_revision = '40316bc3ca16'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outgoing', 'service_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outgoing', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
