"""alter db

Revision ID: 1a5dfe2f9e7d
Revises: 399ffc99ecf2
Create Date: 2015-03-21 15:21:53.088213

"""

# revision identifiers, used by Alembic.
revision = '1a5dfe2f9e7d'
down_revision = '399ffc99ecf2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.alter_column('lead_item', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('lead_item', 'price_from',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=True)
    op.alter_column('lead_item', 'price_to',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lead_item', 'price_to',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=False)
    op.alter_column('lead_item', 'price_from',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=False)
    op.alter_column('lead_item', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    ### end Alembic commands ###
