"""alter db

Revision ID: 1cb89aca614a
Revises: 544ef3a79429
Create Date: 2014-05-17 13:08:45.539415

"""

# revision identifiers, used by Alembic.
revision = '1cb89aca614a'
down_revision = '544ef3a79429'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('descr', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'descr')
    ### end Alembic commands ###
