"""alter db

Revision ID: 1cfe6524723e
Revises: 50f726478887
Create Date: 2014-09-07 18:05:01.272984

"""

# revision identifiers, used by Alembic.
revision = '1cfe6524723e'
down_revision = '50f726478887'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
