"""alter db

Revision ID: 1d805dddc88
Revises: 47b758cd2959
Create Date: 2014-10-04 12:09:09.544308

"""

# revision identifiers, used by Alembic.
revision = '1d805dddc88'
down_revision = '47b758cd2959'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('parent_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'parent_id')
    ### end Alembic commands ###
