"""alter db

Revision ID: 1dfcc639ee50
Revises: None
Create Date: 2014-02-02 17:33:35.924448

"""

# revision identifiers, used by Alembic.
revision = '1dfcc639ee50'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employees_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users')
    op.drop_constraint(None, 'users')
    op.create_index('users_username_key', 'users', [u'username'], unique=True)
    op.create_index('users_email_key', 'users', [u'email'], unique=True)
    op.drop_column('users', 'employees_id')
    op.drop_constraint(None, 'resources_types')
    op.drop_constraint(None, 'resources_types')
    op.create_index('resources_types_name_key', 'resources_types', [u'name'], unique=True)
    op.create_index('resources_types_humanize_key', 'resources_types', [u'humanize'], unique=True)
    op.drop_constraint('unique_idx_resources_types_module', 'resources_types')
    op.create_index('unique_idx_resources_types_module', 'resources_types', [u'module', u'resource_name'], unique=True)
    op.drop_constraint(None, 'groups')
    op.create_index('groups_name_key', 'groups', [u'name'], unique=True)
    op.drop_constraint(None, 'currencies')
    op.create_index('currencies_iso_code_key', 'currencies', [u'iso_code'], unique=True)
    ### end Alembic commands ###
