"""alter db

Revision ID: 1e661947fa33
Revises: 8ea58c1b7416
Create Date: 2016-05-14 20:08:11.282984

"""

# revision identifiers, used by Alembic.
revision = '1e661947fa33'
down_revision = '8ea58c1b7416'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
