"""alter db

Revision ID: 1fb1c1bf90f8
Revises: 49c86cd2e0ff
Create Date: 2015-05-08 22:37:23.109720

"""

# revision identifiers, used by Alembic.
revision = '1fb1c1bf90f8'
down_revision = '49c86cd2e0ff'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.drop_column('commission', 'date_from')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commission', sa.Column('date_from', sa.DATE(), autoincrement=False, nullable=False))
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    ### end Alembic commands ###
