"""alter db

Revision ID: 1fe8e170b6e4
Revises: None
Create Date: 2014-06-13 19:19:40.211581

"""

# revision identifiers, used by Alembic.
revision = '1fe8e170b6e4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_service_item',
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('service_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_item_id'], ['service_item.id'], name='fk_service_item_id_tour_service_item', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['tour_id'], ['tour.id'], name='fk_tour_id_tour_service_item', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('tour_id', 'service_item_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tour_service_item')
    ### end Alembic commands ###
