"""alter db

Revision ID: 2039649e87df
Revises: 276b0cb78799
Create Date: 2014-10-05 21:42:30.952331

"""

# revision identifiers, used by Alembic.
revision = '2039649e87df'
down_revision = '276b0cb78799'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subaccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('descr', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='fk_subaccount_account_id', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name='fk_resource_id_subaccount', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='unique_idx_name_subaccount')
    )
    op.drop_column(u'account', 'parent_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'account', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('subaccount')
    ### end Alembic commands ###
