"""alter db

Revision ID: 24298b9e6a3e
Revises: 161687c38a49
Create Date: 2015-04-25 15:14:05.496240

"""

# revision identifiers, used by Alembic.
revision = '24298b9e6a3e'
down_revision = '161687c38a49'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.drop_table('tour_sale_point')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_sale_point',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('foodcat_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('roomcat_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tour_sale_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('accomodation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('descr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['accomodation_id'], [u'accomodation.id'], name=u'fk_accomodation_id_tour_sale_point'),
    sa.ForeignKeyConstraint(['foodcat_id'], [u'foodcat.id'], name=u'fk_foodcat_id_tour_point', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.ForeignKeyConstraint(['hotel_id'], [u'hotel.id'], name=u'fk_hotel_id_tour_point', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], [u'location.id'], name=u'fk_location_id_tour_point', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.ForeignKeyConstraint(['roomcat_id'], [u'roomcat.id'], name=u'fk_roomcat_id_tour_point', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.ForeignKeyConstraint(['tour_sale_id'], [u'tour_sale.id'], name=u'fk_tour_id_tour_point', onupdate=u'CASCADE', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id', name=u'tour_point_pkey')
    )
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    ### end Alembic commands ###
