"""alter db

Revision ID: 2515d3072f0f
Revises: None
Create Date: 2015-06-10 11:57:31.858861

"""

# revision identifiers, used by Alembic.
revision = '2515d3072f0f'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.add_column('cashflow', sa.Column('vat', sa.Numeric(precision=16, scale=2), nullable=True))
    op.drop_constraint(u'fk_account_to_id_transfer', 'cashflow', type_='foreignkey')
    op.drop_constraint(u'fk_account_from_id_transfer', 'cashflow', type_='foreignkey')
    op.drop_column('cashflow', 'account_to_id')
    op.drop_column('cashflow', 'account_from_id')
    op.create_unique_constraint('unique_idx_name_account_id_subaccount', 'subaccount', ['name', 'account_id'])
    op.drop_constraint(u'unique_idx_name_subaccount', 'subaccount', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'unique_idx_name_subaccount', 'subaccount', ['name'])
    op.drop_constraint('unique_idx_name_account_id_subaccount', 'subaccount', type_='unique')
    op.add_column('cashflow', sa.Column('account_from_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cashflow', sa.Column('account_to_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'fk_account_from_id_transfer', 'cashflow', 'account', ['account_from_id'], ['id'])
    op.create_foreign_key(u'fk_account_to_id_transfer', 'cashflow', 'account', ['account_to_id'], ['id'])
    op.drop_column('cashflow', 'vat')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    ### end Alembic commands ###
