"""alter db

Revision ID: 263e5ee330aa
Revises: 44e139978b26
Create Date: 2015-03-21 19:15:59.774470

"""

# revision identifiers, used by Alembic.
revision = '263e5ee330aa'
down_revision = '44e139978b26'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from travelcrm.lib import EnumIntType

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.add_column('lead', sa.Column('status', EnumIntType()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead', 'status')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    ### end Alembic commands ###
