"""alter db

Revision ID: 26acac2c77cd
Revises: 2515d3072f0f
Create Date: 2015-06-13 12:09:35.257919

"""

# revision identifiers, used by Alembic.
revision = '26acac2c77cd'
down_revision = '2515d3072f0f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_subaccount',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('subaccount_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='fk_company_id_company_subaccount', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['subaccount_id'], ['subaccount.id'], name='fk_subaccount_id_company_subaccount', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('company_id', 'subaccount_id')
    )
    op.drop_table('apscheduler_jobs')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    op.drop_table('company_subaccount')
    ### end Alembic commands ###
