"""alter db

Revision ID: 26e908f23d05
Revises: None
Create Date: 2014-01-03 15:50:03.618685

"""

# revision identifiers, used by Alembic.
revision = '26e908f23d05'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('_resources', '_owner_users_rid',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('_resources', '_owner_users_rid',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
