"""alter db

Revision ID: 276b0cb78799
Revises: 85144dd7ab9
Create Date: 2014-10-04 22:01:49.312603

"""

# revision identifiers, used by Alembic.
revision = '276b0cb78799'
down_revision = '85144dd7ab9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('account_from_id', sa.Integer(), nullable=True),
    sa.Column('account_to_id', sa.Integer(), nullable=True),
    sa.Column('account_item_id', sa.Integer(), nullable=False),
    sa.Column('sum', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.CheckConstraint('account_from_id is not null or account_to_id is not null', name='constraint_at_list_single_account_not_null'),
    sa.ForeignKeyConstraint(['account_from_id'], ['account.id'], name='fk_account_from_id_posting', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['account_item_id'], ['account_item.id'], name='fk_account_item_id_posting', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['account_to_id'], ['account.id'], name='fk_account_to_id_posting', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name='fk_resource_id_posting', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posting')
    ### end Alembic commands ###
