"""alter db

Revision ID: 27fe728cd7c
Revises: 486e28f5f2b8
Create Date: 2014-11-28 21:45:00.993520

"""

# revision identifiers, used by Alembic.
revision = '27fe728cd7c'
down_revision = '486e28f5f2b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('navigation', sa.Column('separator_before', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('navigation', 'separator_before')
    ### end Alembic commands ###
