"""alter db

Revision ID: 282012598f63
Revises: 1fe8e170b6e4
Create Date: 2014-06-14 19:20:42.462537

"""

# revision identifiers, used by Alembic.
revision = '282012598f63'
down_revision = '1fe8e170b6e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_item', sa.Column('base_price', sa.Numeric(precision=16, scale=2), nullable=True))
    op.add_column('tour', sa.Column('base_price', sa.Numeric(precision=16, scale=2), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour', 'base_price')
    op.drop_column('service_item', 'base_price')
    ### end Alembic commands ###
