"""alter db

Revision ID: 2918f8f6e78c
Revises: 1903b058d2ff
Create Date: 2014-04-30 17:47:28.171278

"""

# revision identifiers, used by Alembic.
revision = '2918f8f6e78c'
down_revision = '1903b058d2ff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
