"""alter db

Revision ID: 296f8a6cd318
Revises: None
Create Date: 2015-10-31 14:15:01.234742

"""

# revision identifiers, used by Alembic.
revision = '296f8a6cd318'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaign', 'html_content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('campaign', 'plain_content',
               existing_type=sa.TEXT(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaign', 'plain_content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('campaign', 'html_content',
               existing_type=sa.TEXT(),
               nullable=False)
    ### end Alembic commands ###
