"""alter db

Revision ID: 2ad1be7305c3
Revises: None
Create Date: 2014-09-29 22:11:17.817187

"""

# revision identifiers, used by Alembic.
revision = '2ad1be7305c3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculation_item')
    op.drop_table('calculation')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation',
    sa.Column('id', sa.INTEGER(), server_default="nextval('calculation_id_seq'::regclass)", nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('descr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], [u'resource.id'], name=u'fk_resource_id_liability', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=u'calculation_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('calculation_item',
    sa.Column('id', sa.INTEGER(), server_default="nextval('calculation_item_id_seq'::regclass)", nullable=False),
    sa.Column('calculation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=16, scale=2), autoincrement=False, nullable=False),
    sa.Column('base_price', sa.NUMERIC(precision=16, scale=2), autoincrement=False, nullable=True),
    sa.Column('currency_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['calculation_id'], [u'calculation.id'], name=u'fk_calculation_id_calculation_item', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.ForeignKeyConstraint(['currency_id'], [u'currency.id'], name=u'fk_currency_id_liability_item', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=u'calculation_item_pkey')
    )
    ### end Alembic commands ###
