"""alter db

Revision ID: 2ae6a852f7d6
Revises: 12645ce26efd
Create Date: 2015-03-09 18:48:19.625783

"""

# revision identifiers, used by Alembic.
revision = '2ae6a852f7d6'
down_revision = '12645ce26efd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_notification', 'status',
               existing_type=sa.SMALLINT(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_notification', 'status',
               existing_type=sa.SMALLINT(),
               nullable=True)
    ### end Alembic commands ###
