"""alter db

Revision ID: 2b663248609a
Revises: 26e908f23d05
Create Date: 2014-01-03 15:51:45.840550

"""

# revision identifiers, used by Alembic.
revision = '2b663248609a'
down_revision = '26e908f23d05'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_attachments',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('_resources_rid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['_resources_rid'], ['_resources.rid'], name='fk_resources_rid_attachments', onupdate='cascade', ondelete='cascade', use_alter=True),
    sa.PrimaryKeyConstraint('rid')
    )
    op.create_table('_employees',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('_resources_rid', sa.Integer(), nullable=False),
    sa.Column('_photo_attachments_rid', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('second_name', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['_photo_attachments_rid'], ['_attachments.rid'], name='fk_photo_attachments_rid_employees', onupdate='cascade', ondelete='cascade', use_alter=True),
    sa.ForeignKeyConstraint(['_resources_rid'], ['_resources.rid'], name='fk_resources_rid_employees', onupdate='cascade', ondelete='cascade', use_alter=True),
    sa.PrimaryKeyConstraint('rid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_employees')
    op.drop_table('_attachments')
    ### end Alembic commands ###
