"""alter db

Revision ID: 2b67e623c616
Revises: 3ce07326c5d6
Create Date: 2014-04-28 12:45:34.393779

"""

# revision identifiers, used by Alembic.
revision = '2b67e623c616'
down_revision = '3ce07326c5d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_passport',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('passport_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['passport_id'], ['passport.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('employee_id', 'passport_id')
    )
    op.create_table('employee_contact',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('employee_id', 'contact_id')
    )
    op.create_table('employee_address',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('employee_id', 'address_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_address')
    op.drop_table('employee_contact')
    op.drop_table('employee_passport')
    ### end Alembic commands ###
