"""alter db

Revision ID: 2f28d3d15605
Revises: 4a0fb1407e06
Create Date: 2014-08-17 20:39:43.614126

"""

# revision identifiers, used by Alembic.
revision = '2f28d3d15605'
down_revision = '4a0fb1407e06'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('account_item_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='fk_account_id_refund', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['account_item_id'], ['account_item.id'], name='fk_account_item_id_refund', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name='fk_invoice_id_refund', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name='fk_resource_id_refund', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refund_transaction',
    sa.Column('refund_id', sa.Integer(), nullable=False),
    sa.Column('fin_transaction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fin_transaction_id'], ['fin_transaction.id'], name='fk_fin_transaction_id_refund_transaction', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['refund_id'], ['refund.id'], name='fk_refund_id_refund_transaction', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('refund_id', 'fin_transaction_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refund_transaction')
    op.drop_table('refund')
    ### end Alembic commands ###
