"""alter db

Revision ID: 2fddfccc6bfd
Revises: 2918f8f6e78c
Create Date: 2014-04-30 22:42:35.536717

"""

# revision identifiers, used by Alembic.
revision = '2fddfccc6bfd'
down_revision = '2918f8f6e78c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
