"""alter db

Revision ID: 303d58c665a9
Revises: 32feb251fcb8
Create Date: 2014-09-07 17:58:34.998308

"""

# revision identifiers, used by Alembic.
revision = '303d58c665a9'
down_revision = '32feb251fcb8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('liability_item', 'liability_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('liability_item', 'liability_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
