"""alter db

Revision ID: 309c8478ded6
Revises: 106f13073959
Create Date: 2016-09-03 18:22:15.734792

"""

# revision identifiers, used by Alembic.
revision = '309c8478ded6'
down_revision = '106f13073959'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
