"""alter db

Revision ID: 316c9a430efb
Revises: 537f6e20272f
Create Date: 2015-06-27 20:27:33.950092

"""

# revision identifiers, used by Alembic.
revision = '316c9a430efb'
down_revision = '537f6e20272f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.add_column('upload', sa.Column('descr', sa.String(length=255), nullable=True))
    op.add_column('upload', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('upload', sa.Column('resource_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_resource_id_contact', 'upload', 'resource', ['resource_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_resource_id_contact', 'upload', type_='foreignkey')
    op.drop_column('upload', 'resource_id')
    op.drop_column('upload', 'name')
    op.drop_column('upload', 'descr')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    ### end Alembic commands ###
