"""alter db

Revision ID: 328e8c9b983
Revises: 15e6f8d3ab2c
Create Date: 2015-01-07 12:07:48.887545

"""

# revision identifiers, used by Alembic.
revision = '328e8c9b983'
down_revision = '15e6f8d3ab2c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('structure', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('structure', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
