"""alter db

Revision ID: 32bfd116ec8d
Revises: 50f048a8a1c9
Create Date: 2015-03-21 16:18:55.236324

"""

# revision identifiers, used by Alembic.
revision = '32bfd116ec8d'
down_revision = '50f048a8a1c9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.add_column('lead_item', sa.Column('lead_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_lead_id_lead_item', 'lead_item', 'lead', ['lead_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_lead_id_lead_item', 'lead_item', type_='foreignkey')
    op.drop_column('lead_item', 'lead_id')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    ### end Alembic commands ###
