"""alter db

Revision ID: 32f865aa2c94
Revises: None
Create Date: 2014-10-31 15:32:22.927873

"""

# revision identifiers, used by Alembic.
revision = '32f865aa2c94'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_subaccount',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('subaccount_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='fk_employee_id_employee_subaccount', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['subaccount_id'], ['subaccount.id'], name='fk_subaccount_id_employee_subaccount', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('employee_id', 'subaccount_id')
    )
    op.create_table('touroperator_subaccount',
    sa.Column('touroperator_id', sa.Integer(), nullable=False),
    sa.Column('subaccount_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subaccount_id'], ['subaccount.id'], name='fk_subaccount_id_touroperator_subaccount', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['touroperator_id'], ['touroperator.id'], name='fk_touroperator_id_touroperator_subaccount', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('touroperator_id', 'subaccount_id')
    )
    op.create_table('person_subaccount',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('subaccount_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name='fk_person_id_person_subaccount', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['subaccount_id'], ['subaccount.id'], name='fk_subaccount_id_person_subaccount', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('person_id', 'subaccount_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_subaccount')
    op.drop_table('touroperator_subaccount')
    op.drop_table('employee_subaccount')
    ### end Alembic commands ###
