"""alter db

Revision ID: 32feb251fcb8
Revises: 1554dfca202a
Create Date: 2014-09-07 17:56:43.583716

"""

# revision identifiers, used by Alembic.
revision = '32feb251fcb8'
down_revision = '1554dfca202a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liability_item', sa.Column('service_id', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liability_item', 'service_id')
    ### end Alembic commands ###
