"""alter db

Revision ID: 36d1b5949680
Revises: 3b279a8a50f0
Create Date: 2014-08-16 18:37:15.590790

"""

# revision identifiers, used by Alembic.
revision = '36d1b5949680'
down_revision = '3b279a8a50f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toutgoing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('touroperator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name='fk_resource_id_toutgoing', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['touroperator_id'], ['touroperator.id'], name='fk_touroperator_id_toutgoing', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toutgoing_transactions',
    sa.Column('toutgoing_id', sa.Integer(), nullable=False),
    sa.Column('fin_transaction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fin_transaction_id'], ['fin_transaction.id'], name='fk_fin_transaction_id_toutgoing_transactions', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['toutgoing_id'], ['toutgoing.id'], name='fk_toutgoing_id_toutgoing_transactions', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('toutgoing_id', 'fin_transaction_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toutgoing_transactions')
    op.drop_table('toutgoing')
    ### end Alembic commands ###
