"""alter db

Revision ID: 3714a2ddadd2
Revises: 59c1b648b2bb
Create Date: 2014-10-19 22:22:55.176988

"""

# revision identifiers, used by Alembic.
revision = '3714a2ddadd2'
down_revision = '59c1b648b2bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_sale_service_item',
    sa.Column('tour_sale_id', sa.Integer(), nullable=False),
    sa.Column('service_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_item_id'], ['service_item.id'], name='fk_service_item_id_tour_sale_service_item', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['tour_sale_id'], ['tour_sale.id'], name='fk_tour_sale_id_tour_sale_service_item', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('tour_sale_id', 'service_item_id')
    )
    op.drop_table('tour_service_item')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_service_item',
    sa.Column('tour_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['service_item_id'], [u'service_item.id'], name=u'fk_service_item_id_tour_service_item', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.ForeignKeyConstraint(['tour_id'], [u'tour_sale.id'], name=u'fk_tour_id_tour_service_item', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.PrimaryKeyConstraint('tour_id', 'service_item_id', name=u'tour_service_item_pkey')
    )
    op.drop_table('tour_sale_service_item')
    ### end Alembic commands ###
