"""alter db

Revision ID: 37790c742951
Revises: None
Create Date: 2014-04-23 21:02:21.913632

"""

# revision identifiers, used by Alembic.
revision = '37790c742951'
down_revision = None

from alembic import op
import sqlalchemy as sa
from travelcrm.lib import EnumIntType


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('status', EnumIntType(), nullable=False))
    op.drop_column('task', 'closed')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('closed', sa.BOOLEAN(), nullable=True))
    op.drop_column('task', 'status')
    ### end Alembic commands ###
