"""alter db

Revision ID: 399ffc99ecf2
Revises: 45f5d49f9433
Create Date: 2015-03-21 15:06:48.584499

"""

# revision identifiers, used by Alembic.
revision = '399ffc99ecf2'
down_revision = '45f5d49f9433'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('price_from', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('price_to', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('descr', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], name='fk_currency_id_lead_item', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name='fk_resource_id_lead_item', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name='fk_service_id_lead_item', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('apscheduler_jobs')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    op.drop_table('lead_item')
    ### end Alembic commands ###
