"""alter db

Revision ID: 39b91c3229bf
Revises: 41adaf804a94
Create Date: 2014-09-14 13:21:37.850172

"""

# revision identifiers, used by Alembic.
revision = '39b91c3229bf'
down_revision = '41adaf804a94'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liability_item', sa.Column('base_price', sa.Numeric(precision=16, scale=2), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liability_item', 'base_price')
    ### end Alembic commands ###
