"""alter db

Revision ID: 3a4b3406bbdd
Revises: 487b34a215af
Create Date: 2014-04-12 18:58:49.783676

"""

# revision identifiers, used by Alembic.
revision = '3a4b3406bbdd'
down_revision = '487b34a215af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour', sa.Column('deal_date', sa.Date(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour', 'deal_date')
    ### end Alembic commands ###
