"""alter db

Revision ID: 3a70007cbc68
Revises: 4ed679002e2e
Create Date: 2014-11-15 10:54:07.744111

"""

# revision identifiers, used by Alembic.
revision = '3a70007cbc68'
down_revision = '4ed679002e2e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crosspayment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('descr', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name='fk_resource_id_crosspayment', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer.id'], name='fk_transfer_id_crosspayment', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('posting')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posting',
    sa.Column('id', sa.INTEGER(), server_default="nextval('posting_id_seq'::regclass)", nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('account_from_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('account_to_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('account_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sum', sa.NUMERIC(precision=16, scale=2), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_from_id'], [u'account.id'], name=u'fk_account_from_id_posting', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.ForeignKeyConstraint(['account_item_id'], [u'account_item.id'], name=u'fk_account_item_id_posting', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.ForeignKeyConstraint(['account_to_id'], [u'account.id'], name=u'fk_account_to_id_posting', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.ForeignKeyConstraint(['resource_id'], [u'resource.id'], name=u'fk_resource_id_posting', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=u'posting_pkey')
    )
    op.drop_table('crosspayment')
    ### end Alembic commands ###
