"""alter db

Revision ID: 3b279a8a50f0
Revises: 59a442cc5fdc
Create Date: 2014-07-02 19:56:30.570539

"""

# revision identifiers, used by Alembic.
revision = '3b279a8a50f0'
down_revision = '59a442cc5fdc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('structure', 'invoice_template')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('structure', sa.Column('invoice_template', sa.TEXT(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
