"""alter db

Revision ID: 3b4755fe841
Revises: None
Create Date: 2014-02-08 15:59:35.536902

"""

# revision identifiers, used by Alembic.
revision = '3b4755fe841'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('structure_id', sa.Integer(), nullable=True))
    op.drop_column('resource', u'owner_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_idx_users_username', 'user')
    op.create_index('unique_idx_users_username', 'user', [u'username'], unique=True)
    op.drop_constraint('unique_idx_users_email', 'user')
    op.create_index('unique_idx_users_email', 'user', [u'email'], unique=True)
    op.drop_constraint(None, 'resource_type')
    op.create_index('resource_type_name_key', 'resource_type', [u'name'], unique=True)
    op.drop_constraint('unique_idx_resource_type_name', 'resource_type')
    op.create_index('unique_idx_resource_type_name', 'resource_type', [u'name'], unique=True)
    op.drop_constraint('unique_idx_resource_type_module', 'resource_type')
    op.create_index('unique_idx_resource_type_module', 'resource_type', [u'module', u'resource_name'], unique=True)
    op.add_column('resource', sa.Column(u'owner_id', sa.INTEGER(), nullable=False))
    op.drop_column('resource', 'structure_id')
    op.drop_constraint('unique_idx_currency_iso_code', 'currency')
    op.create_index('unique_idx_currency_iso_code', 'currency', [u'iso_code'], unique=True)
    ### end Alembic commands ###
