"""alter db

Revision ID: 3ce07326c5d6
Revises: e4fdb3f65a6
Create Date: 2014-04-28 12:28:56.294480

"""

# revision identifiers, used by Alembic.
revision = '3ce07326c5d6'
down_revision = 'e4fdb3f65a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('itn', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'itn')
    ### end Alembic commands ###
