"""alter db

Revision ID: 3d04ef2ed0fa
Revises: 42629f8c7b15
Create Date: 2014-04-19 13:03:37.832385

"""

# revision identifiers, used by Alembic.
revision = '3d04ef2ed0fa'
down_revision = '42629f8c7b15'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'descr',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'descr',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###
