"""alter db

Revision ID: 3df3b48fc5e
Revises: 12c18b2f59ac
Create Date: 2014-04-29 09:49:29.483544

"""

# revision identifiers, used by Alembic.
revision = '3df3b48fc5e'
down_revision = '12c18b2f59ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('structure_contact',
    sa.Column('structure_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['structure_id'], ['structure.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('structure_id', 'contact_id')
    )
    op.create_table('structure_bank_detail',
    sa.Column('structure_id', sa.Integer(), nullable=False),
    sa.Column('bank_detail_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_detail_id'], ['bank_detail.id'], onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['structure_id'], ['structure.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('structure_id', 'bank_detail_id')
    )
    op.create_table('structure_address',
    sa.Column('structure_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['structure_id'], ['structure.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('structure_id', 'address_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('structure_address')
    op.drop_table('structure_bank_detail')
    op.drop_table('structure_contact')
    ### end Alembic commands ###
