"""alter db

Revision ID: 3ef04f81797a
Revises: 2b67e623c616
Create Date: 2014-04-28 13:47:48.089582

"""

# revision identifiers, used by Alembic.
revision = '3ef04f81797a'
down_revision = '2b67e623c616'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('currency_id', sa.Integer(), nullable=True))
    op.add_column('appointment', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.add_column('appointment', sa.Column('position_id', sa.Integer(), nullable=True))
    op.add_column('appointment', sa.Column('salary', sa.Numeric(precision=16, scale=2), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'salary')
    op.drop_column('appointment', 'position_id')
    op.drop_column('appointment', 'employee_id')
    op.drop_column('appointment', 'currency_id')
    ### end Alembic commands ###
