"""alter db

Revision ID: 3fe1f65fcaf
Revises: 3a3565b1ba02
Create Date: 2014-03-16 18:52:03.714470

"""

# revision identifiers, used by Alembic.
revision = '3fe1f65fcaf'
down_revision = '3a3565b1ba02'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('resource_id', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_idx_users_username', 'user')
    op.create_index('unique_idx_users_username', 'user', [u'username'], unique=True)
    op.drop_constraint('unique_idx_users_email', 'user')
    op.create_index('unique_idx_users_email', 'user', [u'email'], unique=True)
    op.drop_constraint(None, 'resource_type')
    op.create_index('resource_type_name_key', 'resource_type', [u'name'], unique=True)
    op.drop_constraint('unique_idx_resource_type_name', 'resource_type')
    op.create_index('unique_idx_resource_type_name', 'resource_type', [u'name'], unique=True)
    op.drop_constraint('unique_idx_resource_type_module', 'resource_type')
    op.create_index('unique_idx_resource_type_module', 'resource_type', [u'module', u'resource_name'], unique=True)
    op.drop_constraint('unique_idx_currency_iso_code', 'currency')
    op.create_index('unique_idx_currency_iso_code', 'currency', [u'iso_code'], unique=True)
    op.drop_column('contact', 'resource_id')
    ### end Alembic commands ###
