"""alter db

Revision ID: 40316bc3ca16
Revises: 4a9b20b3e821
Create Date: 2014-10-01 21:44:18.586886

"""

# revision identifiers, used by Alembic.
revision = '40316bc3ca16'
down_revision = '4a9b20b3e821'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outgoing', sa.Column('service_id', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outgoing', 'service_id')
    ### end Alembic commands ###
