"""alter db

Revision ID: 41adaf804a94
Revises: 1cfe6524723e
Create Date: 2014-09-14 09:47:35.465584

"""

# revision identifiers, used by Alembic.
revision = '41adaf804a94'
down_revision = '1cfe6524723e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('explicit', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'explicit')
    ### end Alembic commands ###
