"""alter db

Revision ID: 41d144e9292d
Revises: 2ae6a852f7d6
Create Date: 2015-03-09 18:52:53.318023

"""

# revision identifiers, used by Alembic.
revision = '41d144e9292d'
down_revision = '2ae6a852f7d6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_resource',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], name='fk_notification_id_notification_resource', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name='fk_resource_id_notification_resource', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('notification_id', 'resource_id')
    )
    op.drop_table('apscheduler_jobs')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    op.drop_table('notification_resource')
    ### end Alembic commands ###
