"""alter db

Revision ID: 42629f8c7b15
Revises: 7fae44a4ebc
Create Date: 2014-04-19 10:08:31.830664

"""

# revision identifiers, used by Alembic.
revision = '42629f8c7b15'
down_revision = '7fae44a4ebc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_resource',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('task_id', 'resource_id')
    )
    op.drop_column(u'task', 'task_resource_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'task', sa.Column('task_resource_id', sa.INTEGER(), nullable=True))
    op.drop_table('task_resource')
    ### end Alembic commands ###
