"""alter db

Revision ID: 42dc01faf677
Revises: 27698df43d10
Create Date: 2015-03-07 13:44:58.687916

"""

# revision identifiers, used by Alembic.
revision = '42dc01faf677'
down_revision = '27698df43d10'

from alembic import op
import sqlalchemy as sa

from travelcrm.lib import EnumIntType

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_type', sa.Column('status', EnumIntType(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_type', 'status')
    ### end Alembic commands ###
