"""alter db

Revision ID: 43168ad6ab56
Revises: 35f5326bfa88
Create Date: 2014-12-13 19:37:23.032795

"""

# revision identifiers, used by Alembic.
revision = '43168ad6ab56'
down_revision = '35f5326bfa88'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('descr', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='fk_employee_id_notification', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    ### end Alembic commands ###
