"""alter db

Revision ID: 4327c5c76f29
Revises: None
Create Date: 2014-04-12 16:54:36.559940

"""

# revision identifiers, used by Alembic.
revision = '4327c5c76f29'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_person',
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['tour_id'], ['tour.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('tour_id', 'person_id')
    )
    op.add_column(u'tour', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.add_column(u'tour', sa.Column('resource_id', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'tour', 'resource_id')
    op.drop_column(u'tour', 'customer_id')
    op.drop_table('tour_person')
    ### end Alembic commands ###
