"""alter db

Revision ID: 43cdee2b7f13
Revises: 808944506f8
Create Date: 2014-08-16 19:49:28.500266

"""

# revision identifiers, used by Alembic.
revision = '43cdee2b7f13'
down_revision = '808944506f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name='fk_resource_id_supplier', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='unique_idx_name_supplier')
    )
    op.create_table('supplier_bperson',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('bperson_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bperson_id'], ['bperson.id'], name='fk_bperson_id_supplier_bperson', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name='fk_supplier_id_supplier_bperson', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('supplier_id', 'bperson_id')
    )
    op.create_table('supplier_bank_detail',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('bank_detail_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_detail_id'], ['bank_detail.id'], name='fk_bank_detail_id_supplier_bank_detail', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name='fk_supplier_id_supplier_bank_detail', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('supplier_id', 'bank_detail_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_bank_detail')
    op.drop_table('supplier_bperson')
    op.drop_table('supplier')
    ### end Alembic commands ###
