"""alter db

Revision ID: 445be8452ecd
Revises: 49f822c6e518
Create Date: 2014-01-04 20:06:24.061827

"""

# revision identifiers, used by Alembic.
revision = '445be8452ecd'
down_revision = '49f822c6e518'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_companies_structures',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('_resources_rid', sa.Integer(), nullable=False),
    sa.Column('_companies_rid', sa.Integer(), nullable=False),
    sa.Column('_companies_structures_rid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['_companies_rid'], ['_companies.rid'], name='fk_companies_rid_companies_structures', onupdate='cascade', ondelete='cascade', use_alter=True),
    sa.ForeignKeyConstraint(['_companies_structures_rid'], ['_companies_structures.rid'], name='fk_companies_structures_companies_structures_rid', onupdate='cascade', ondelete='cascade', use_alter=True),
    sa.ForeignKeyConstraint(['_resources_rid'], ['_resources.rid'], name='fk_resources_rid_companies_structures', onupdate='cascade', ondelete='cascade', use_alter=True),
    sa.PrimaryKeyConstraint('rid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_companies_structures')
    ### end Alembic commands ###
