"""alter db

Revision ID: 447962be6863
Revises: 327edd39edbd
Create Date: 2015-04-26 21:16:02.368707

"""

# revision identifiers, used by Alembic.
revision = '447962be6863'
down_revision = '327edd39edbd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from travelcrm.lib import EnumIntType

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.add_column('order_item', sa.Column('status', EnumIntType(), nullable=True))
    op.add_column('order_item', sa.Column('status_date', sa.Date(), nullable=True))
    op.add_column('order_item', sa.Column('status_info', sa.String(length=128), nullable=True))
    op.drop_column('order_item', 'confirmation')
    op.drop_column('order_item', 'confirmation_id')
    op.drop_column('order_item', 'confirmation_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('confirmation_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('order_item', sa.Column('confirmation_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('order_item', sa.Column('confirmation', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('order_item', 'status_info')
    op.drop_column('order_item', 'status_date')
    op.drop_column('order_item', 'status')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    ### end Alembic commands ###
