"""alter db

Revision ID: 458a53485c18
Revises: 27fe728cd7c
Create Date: 2014-12-07 12:55:50.061844

"""

# revision identifiers, used by Alembic.
revision = '458a53485c18'
down_revision = '27fe728cd7c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('closed', sa.Boolean(), nullable=True))
    op.drop_column('task', 'status')
    op.drop_column('task', 'priority')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.drop_column('task', 'closed')
    ### end Alembic commands ###
