"""alter db

Revision ID: 45f5d49f9433
Revises: 3d21723b3954
Create Date: 2015-03-15 19:16:02.501764

"""

# revision identifiers, used by Alembic.
revision = '45f5d49f9433'
down_revision = '3d21723b3954'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.alter_column('passport', 'passport_type',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('passport', 'passport_type_1')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passport', sa.Column('passport_type_1', postgresql.ENUM(u'citizen', u'foreign', name='passport_type_enum'), autoincrement=False, nullable=False))
    op.alter_column('passport', 'passport_type',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    ### end Alembic commands ###
