"""alter db

Revision ID: 46613352f250
Revises: 16963b42ef74
Create Date: 2014-04-28 15:02:07.006421

"""

# revision identifiers, used by Alembic.
revision = '46613352f250'
down_revision = '16963b42ef74'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('dismissal_date', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'dismissal_date')
    ### end Alembic commands ###
