"""alter db

Revision ID: 478e038fdb69
Revises: 296f8a6cd318
Create Date: 2015-10-31 14:15:56.857874

"""

# revision identifiers, used by Alembic.
revision = '478e038fdb69'
down_revision = '296f8a6cd318'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resource_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('descr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], [u'resource.id'], name=u'fk_resource_id_lead_type', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.ForeignKeyConstraint(['resource_type_id'], [u'resource_type.id'], name=u'fk_resource_type_id_lead_type', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=u'lead_type_pkey'),
    sa.UniqueConstraint('name', name=u'unique_idx_name_lead_type')
    )
    ### end Alembic commands ###
