"""alter db

Revision ID: 486e28f5f2b8
Revises: 3a70007cbc68
Create Date: 2014-11-23 18:24:21.659572

"""

# revision identifiers, used by Alembic.
revision = '486e28f5f2b8'
down_revision = '3a70007cbc68'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outgoing', 'account_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outgoing', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
