"""alter db

Revision ID: 4874552ee255
Revises: 250bc21d98ef
Create Date: 2015-06-15 20:18:35.047898

"""

# revision identifiers, used by Alembic.
revision = '4874552ee255'
down_revision = '250bc21d98ef'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.drop_constraint(u'fk_currency_id_service_item', 'calculation', type_='foreignkey')
    op.drop_column('calculation', 'currency_id')
    op.drop_column('calculation', 'base_price')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculation', sa.Column('base_price', sa.NUMERIC(precision=16, scale=2), autoincrement=False, nullable=False))
    op.add_column('calculation', sa.Column('currency_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(u'fk_currency_id_service_item', 'calculation', 'currency', ['currency_id'], ['id'])
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    ### end Alembic commands ###
