"""alter db

Revision ID: 49f822c6e518
Revises: 2b663248609a
Create Date: 2014-01-04 19:36:53.465649

"""

# revision identifiers, used by Alembic.
revision = '49f822c6e518'
down_revision = '2b663248609a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_companies',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('_resources_rid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['_resources_rid'], ['_resources.rid'], name='fk_resources_rid_companies', onupdate='cascade', ondelete='cascade', use_alter=True),
    sa.PrimaryKeyConstraint('rid')
    )
    op.alter_column(u'_resources_types', 'name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'_resources_types', 'name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.drop_table('_companies')
    ### end Alembic commands ###
