"""alter db

Revision ID: 4a0fb1407e06
Revises: 1107401a9ac6
Create Date: 2014-08-17 19:34:07.078520

"""

# revision identifiers, used by Alembic.
revision = '4a0fb1407e06'
down_revision = '1107401a9ac6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outgoing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('account_item_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='fk_account_id_outgoing', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['account_item_id'], ['account_item.id'], name='fk_account_item_id_outgoing', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['invoice_id'], ['touroperator.id'], name='fk_touroperator_id_outgoing', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name='fk_resource_id_outgoing', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outgoing_transaction',
    sa.Column('outgoing_id', sa.Integer(), nullable=False),
    sa.Column('fin_transaction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fin_transaction_id'], ['fin_transaction.id'], name='fk_fin_transaction_id_outgoing_transaction', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['outgoing_id'], ['outgoing.id'], name='fk_outgoing_id_outgoing_transaction', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('outgoing_id', 'fin_transaction_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outgoing_transaction')
    op.drop_table('outgoing')
    ### end Alembic commands ###
