"""alter db

Revision ID: 4a9b20b3e821
Revises: 46698cf6cd09
Create Date: 2014-10-01 21:05:20.715981

"""

# revision identifiers, used by Alembic.
revision = '4a9b20b3e821'
down_revision = '46698cf6cd09'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fin_transaction', 'factor',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fin_transaction', 'factor',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
