"""alter db

Revision ID: 4ae38fe41ca
Revises: 4cfd87a8dfa3
Create Date: 2014-06-28 17:09:38.485277

"""

# revision identifiers, used by Alembic.
revision = '4ae38fe41ca'
down_revision = '4cfd87a8dfa3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commission', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('commission', 'percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('commission', 'price',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commission', 'price',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=True)
    op.alter_column('commission', 'percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('commission', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
