"""alter db

Revision ID: 4ba7ec05fb
Revises: None
Create Date: 2014-05-24 23:17:45.631114

"""

# revision identifiers, used by Alembic.
revision = '4ba7ec05fb'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
