"""alter db

Revision ID: 4c0445e408e1
Revises: 536cc8aa2a1f
Create Date: 2015-04-26 00:16:30.888789

"""

# revision identifiers, used by Alembic.
revision = '4c0445e408e1'
down_revision = '536cc8aa2a1f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.add_column('tour', sa.Column('end_additional_info', sa.String(length=128), nullable=True))
    op.add_column('tour', sa.Column('start_additional_info', sa.String(length=128), nullable=True))
    op.drop_column('tour', 'start_transport_info')
    op.drop_column('tour', 'end_transport_info')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour', sa.Column('end_transport_info', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('tour', sa.Column('start_transport_info', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('tour', 'start_additional_info')
    op.drop_column('tour', 'end_additional_info')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    ### end Alembic commands ###
