"""alter db

Revision ID: 4c57f27bc4ad
Revises: 50b045021a4d
Create Date: 2015-06-28 15:42:45.528909

"""

# revision identifiers, used by Alembic.
revision = '4c57f27bc4ad'
down_revision = '50b045021a4d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_upload',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], name='fk_note_id_note_upload', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload.id'], name='fk_upload_id_note_upload', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('note_id', 'upload_id')
    )
    op.create_table('task_upload',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='fk_task_id_task_upload', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload.id'], name='fk_upload_id_task_upload', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('task_id', 'upload_id')
    )
    op.drop_table('apscheduler_jobs')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    op.drop_table('task_upload')
    op.drop_table('note_upload')
    ### end Alembic commands ###
