"""alter db

Revision ID: 4ce38b356bad
Revises: None
Create Date: 2014-12-27 14:06:48.384799

"""

# revision identifiers, used by Alembic.
revision = '4ce38b356bad'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.alter_column('email_campaign', 'subject',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.add_column('invoice', sa.Column('last_payment_date', sa.Date(), nullable=True))
    op.create_foreign_key('fk_account_item_id_outgoing', 'outgoing', 'account_item', ['account_item_id'], ['id'])
    op.create_foreign_key('fk_subaccount_id_outgoing', 'outgoing', 'subaccount', ['subaccount_id'], ['id'])
    op.create_foreign_key('fk_person_id_service_item', 'service_item', 'person', ['person_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_person_id_service_item', 'service_item', type_='foreignkey')
    op.drop_constraint('fk_subaccount_id_outgoing', 'outgoing', type_='foreignkey')
    op.drop_constraint('fk_account_item_id_outgoing', 'outgoing', type_='foreignkey')
    op.drop_column('invoice', 'last_payment_date')
    op.alter_column('email_campaign', 'subject',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    ### end Alembic commands ###
