"""alter db

Revision ID: 4ed679002e2e
Revises: cac2848ba45
Create Date: 2014-11-14 11:55:16.893551

"""

# revision identifiers, used by Alembic.
revision = '4ed679002e2e'
down_revision = 'cac2848ba45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refund_transfer')
    op.drop_table('refund')
    op.add_column('outgoing', sa.Column('account_item_id', sa.Integer(), nullable=False))
    op.add_column('outgoing', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('outgoing', sa.Column('subaccount_id', sa.Integer(), nullable=False))
    op.add_column('outgoing', sa.Column('sum', sa.Numeric(precision=16, scale=2), nullable=False))
    op.drop_column('outgoing', 'touroperator_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outgoing', sa.Column('touroperator_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('outgoing', 'sum')
    op.drop_column('outgoing', 'subaccount_id')
    op.drop_column('outgoing', 'date')
    op.drop_column('outgoing', 'account_item_id')
    op.create_table('refund',
    sa.Column('id', sa.INTEGER(), server_default="nextval('refund_id_seq'::regclass)", nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], [u'invoice.id'], name=u'fk_invoice_id_refund', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.ForeignKeyConstraint(['resource_id'], [u'resource.id'], name=u'fk_resource_id_refund', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=u'refund_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('refund_transfer',
    sa.Column('refund_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transfer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['refund_id'], [u'refund.id'], name=u'fk_refund_id_refund_transfer', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.ForeignKeyConstraint(['transfer_id'], [u'transfer.id'], name=u'fk_transfer_id_refund_transfer', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.PrimaryKeyConstraint('refund_id', 'transfer_id', name=u'refund_transfer_pkey')
    )
    ### end Alembic commands ###
