"""alter db

Revision ID: 4efb33045f18
Revises: 585291a3f82
Create Date: 2014-10-25 22:46:37.021461

"""

# revision identifiers, used by Alembic.
revision = '4efb33045f18'
down_revision = '585291a3f82'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculation', sa.Column('base_price', sa.Numeric(precision=16, scale=2), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calculation', 'base_price')
    ### end Alembic commands ###
