"""alter db

Revision ID: 4fc64487269e
Revises: None
Create Date: 2015-05-08 21:12:36.080865

"""

# revision identifiers, used by Alembic.
revision = '4fc64487269e'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_commission',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('commission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commission_id'], ['commission.id'], name='fk_commission_id_supplier_commission', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name='fk_supplier_id_supplier_commission', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('supplier_id', 'commission_id')
    )
    op.create_table('supplier_contract',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], name='fk_contract_id_supplier_contract', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name='fk_supplier_id_supplier_contract', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('supplier_id', 'contract_id')
    )
    op.create_table('supplier_bank_detail',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('bank_detail_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_detail_id'], ['bank_detail.id'], name='fk_bank_detail_id_supplier_bank_detail', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name='fk_supplier_id_supplier_bank_detail', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('supplier_id', 'bank_detail_id')
    )
    op.create_table('supplier_subaccount',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('subaccount_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subaccount_id'], ['subaccount.id'], name='fk_subaccount_id_supplier_subaccount', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name='fk_supplier_id_supplier_subaccount', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('supplier_id', 'subaccount_id')
    )
    op.create_table('supplier_bperson',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('bperson_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bperson_id'], ['bperson.id'], name='fk_bperson_id_supplier_bperson', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name='fk_supplier_id_supplier_bperson', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('supplier_id', 'bperson_id')
    )
    op.drop_table('apscheduler_jobs')
    op.drop_table('touroperator_contract')
    op.drop_table('touroperator_subaccount')
    op.drop_table('touroperator_bperson')
    op.drop_table('touroperator_bank_detail')
    op.add_column('currency_rate', sa.Column('supplier_id', sa.Integer(), nullable=False))
    op.drop_constraint(u'unique_idx_currency_rate_currency_id_date', 'currency_rate', type_='unique')
    op.create_unique_constraint('unique_idx_currency_rate_currency_id_date', 'currency_rate', ['currency_id', 'date', 'supplier_id'])
    op.drop_constraint(u'fk_touroperator_id_currency_rate', 'currency_rate', type_='foreignkey')
    op.create_foreign_key('fk_supplier_id_currency_rate', 'currency_rate', 'supplier', ['supplier_id'], ['id'])
    op.drop_column('currency_rate', 'touroperator_id')
    op.add_column('order_item', sa.Column('supplier_id', sa.Integer(), nullable=False))
    op.drop_constraint(u'fk_touroperator_id_order_item', 'order_item', type_='foreignkey')
    op.create_foreign_key('fk_supplier_id_order_item', 'order_item', 'supplier', ['supplier_id'], ['id'])
    op.drop_column('order_item', 'touroperator_id')
    op.create_unique_constraint('unique_idx_name_supplier', 'supplier', ['name'])
    op.drop_constraint(u'unique_idx_name_touroperator', 'supplier', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'unique_idx_name_touroperator', 'supplier', ['name'])
    op.drop_constraint('unique_idx_name_supplier', 'supplier', type_='unique')
    op.add_column('order_item', sa.Column('touroperator_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_supplier_id_order_item', 'order_item', type_='foreignkey')
    op.create_foreign_key(u'fk_touroperator_id_order_item', 'order_item', 'supplier', ['touroperator_id'], ['id'])
    op.drop_column('order_item', 'supplier_id')
    op.add_column('currency_rate', sa.Column('touroperator_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_supplier_id_currency_rate', 'currency_rate', type_='foreignkey')
    op.create_foreign_key(u'fk_touroperator_id_currency_rate', 'currency_rate', 'supplier', ['touroperator_id'], ['id'])
    op.drop_constraint('unique_idx_currency_rate_currency_id_date', 'currency_rate', type_='unique')
    op.create_unique_constraint(u'unique_idx_currency_rate_currency_id_date', 'currency_rate', ['currency_id', 'date', 'touroperator_id'])
    op.drop_column('currency_rate', 'supplier_id')
    op.create_table('touroperator_bank_detail',
    sa.Column('touroperator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bank_detail_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bank_detail_id'], [u'bank_detail.id'], name=u'fk_bank_detail_id_touroperator_bank_detail', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.ForeignKeyConstraint(['touroperator_id'], [u'supplier.id'], name=u'fk_touroperator_id_touroperator_bank_detail', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.PrimaryKeyConstraint('touroperator_id', 'bank_detail_id', name=u'touroperator_bank_detail_pkey')
    )
    op.create_table('touroperator_bperson',
    sa.Column('touroperator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bperson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bperson_id'], [u'bperson.id'], name=u'fk_bperson_id_touroperator_bperson', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.ForeignKeyConstraint(['touroperator_id'], [u'supplier.id'], name=u'fk_touroperator_id_touroperator_bperson', onupdate=u'CASCADE', ondelete=u'RESTRICT')
    )
    op.create_table('touroperator_subaccount',
    sa.Column('touroperator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subaccount_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subaccount_id'], [u'subaccount.id'], name=u'fk_subaccount_id_touroperator_subaccount', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.ForeignKeyConstraint(['touroperator_id'], [u'supplier.id'], name=u'fk_touroperator_id_touroperator_subaccount', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.PrimaryKeyConstraint('touroperator_id', 'subaccount_id', name=u'touroperator_subaccount_pkey')
    )
    op.create_table('touroperator_contract',
    sa.Column('touroperator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], [u'contract.id'], name=u'fk_contract_id_touroperator_contract', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.ForeignKeyConstraint(['touroperator_id'], [u'supplier.id'], name=u'fk_touroperator_id_touroperator_contract', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.PrimaryKeyConstraint('touroperator_id', 'contract_id', name=u'touroperator_contract_pkey')
    )
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    op.drop_table('supplier_bperson')
    op.drop_table('supplier_subaccount')
    op.drop_table('supplier_bank_detail')
    op.drop_table('supplier_contract')
    op.drop_table('supplier_commission')
    ### end Alembic commands ###
