"""alter db

Revision ID: 5075716173ca
Revises: None
Create Date: 2015-04-22 14:44:43.674754

"""

# revision identifiers, used by Alembic.
revision = '5075716173ca'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outgoing_cashflow',
    sa.Column('outgoing_id', sa.Integer(), nullable=False),
    sa.Column('cashflow_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cashflow_id'], ['cashflow.id'], name='fk_cashflow_id_outgoing_cashflow', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['outgoing_id'], ['outgoing.id'], name='fk_outgoing_id_outgoing_cashflow', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('outgoing_id', 'cashflow_id')
    )
    op.create_table('income_cashflow',
    sa.Column('income_id', sa.Integer(), nullable=False),
    sa.Column('cashflow_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cashflow_id'], ['cashflow.id'], name='fk_cashflow_id_income_cashflow', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['income_id'], ['income.id'], name='fk_income_id_income_cashflow', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('income_id', 'cashflow_id')
    )
    op.drop_table('outgoing_transfer')
    op.drop_table('apscheduler_jobs')
    op.drop_table('income_transfer')
    op.create_foreign_key('fk_cashflow_id_crosspayment', 'crosspayment', 'cashflow', ['cashflow_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_cashflow_id_crosspayment', 'crosspayment', type_='foreignkey')
    op.create_table('income_transfer',
    sa.Column('income_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transfer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['income_id'], [u'income.id'], name=u'fk_income_id_income_transfer', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.ForeignKeyConstraint(['transfer_id'], [u'cashflow.id'], name=u'fk_transfer_id_income_transfer', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.PrimaryKeyConstraint('income_id', 'transfer_id', name=u'income_transfer_pkey')
    )
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    op.create_table('outgoing_transfer',
    sa.Column('outgoing_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transfer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['outgoing_id'], [u'outgoing.id'], name=u'fk_outgoing_id_outgoing_transfer', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.ForeignKeyConstraint(['transfer_id'], [u'cashflow.id'], name=u'fk_transfer_id_outgoing_transfer', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.PrimaryKeyConstraint('outgoing_id', 'transfer_id', name=u'outgoing_transfer_pkey')
    )
    op.drop_table('income_cashflow')
    op.drop_table('outgoing_cashflow')
    ### end Alembic commands ###
