"""alter db

Revision ID: 50b045021a4d
Revises: 316c9a430efb
Create Date: 2015-06-27 20:32:25.084617

"""

# revision identifiers, used by Alembic.
revision = '50b045021a4d'
down_revision = '316c9a430efb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
