"""alter db

Revision ID: 50c57c8f2380
Revises: 4fc64487269e
Create Date: 2015-05-08 21:52:20.264827

"""

# revision identifiers, used by Alembic.
revision = '50c57c8f2380'
down_revision = '4fc64487269e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from travelcrm.lib import EnumIntType

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_commission',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('commission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commission_id'], ['commission.id'], name='fk_commission_id_contract_commission', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], name='fk_contract_id_contract_commission', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('contract_id', 'commission_id')
    )
    op.drop_table('apscheduler_jobs')
    op.drop_table('supplier_commission')
    op.add_column('contract', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('contract', sa.Column('num', sa.String(), nullable=False))
    op.drop_column('contract', 'date_from')
    op.drop_column('contract', 'contract_num')
    op.drop_column('contract', 'date_to')
    op.add_column('supplier', sa.Column('status', EnumIntType(), nullable=False))
    op.drop_constraint(u'unique_idx_name_supplier', 'supplier', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'unique_idx_name_supplier', 'supplier', ['name'])
    op.drop_column('supplier', 'status')
    op.add_column('contract', sa.Column('date_to', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('contract', sa.Column('contract_num', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('contract', sa.Column('date_from', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('contract', 'num')
    op.drop_column('contract', 'date')
    op.create_table('supplier_commission',
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('commission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['commission_id'], [u'commission.id'], name=u'fk_commission_id_supplier_commission', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], [u'supplier.id'], name=u'fk_supplier_id_supplier_commission', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.PrimaryKeyConstraint('supplier_id', 'commission_id', name=u'supplier_commission_pkey')
    )
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    op.drop_table('contract_commission')
    ### end Alembic commands ###
