"""alter db

Revision ID: 50f048a8a1c9
Revises: 1a5dfe2f9e7d
Create Date: 2015-03-21 15:25:50.157821

"""

# revision identifiers, used by Alembic.
revision = '50f048a8a1c9'
down_revision = '1a5dfe2f9e7d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
