"""alter db

Revision ID: 50f726478887
Revises: 303d58c665a9
Create Date: 2014-09-07 18:00:49.133912

"""

# revision identifiers, used by Alembic.
revision = '50f726478887'
down_revision = '303d58c665a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liability_item', 'date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liability_item', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
