"""alter db

Revision ID: 528bd115509c
Revises: 55bedab769b6
Create Date: 2014-09-14 21:16:33.238562

"""

# revision identifiers, used by Alembic.
revision = '528bd115509c'
down_revision = '55bedab769b6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outgoing', sa.Column('touroperator_id', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outgoing', 'touroperator_id')
    ### end Alembic commands ###
