"""alter db

Revision ID: 536cc8aa2a1f
Revises: ef3412b067f
Create Date: 2015-04-25 22:53:51.508370

"""

# revision identifiers, used by Alembic.
revision = '536cc8aa2a1f'
down_revision = 'ef3412b067f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.drop_constraint(u'fk_location_id_tour', 'tour', type_='foreignkey')
    op.drop_column('tour', 'location_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour', sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(u'fk_location_id_tour', 'tour', 'location', ['location_id'], ['id'])
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    ### end Alembic commands ###
