"""alter db

Revision ID: 537f6e20272f
Revises: None
Create Date: 2015-06-27 19:30:27.789057

"""

# revision identifiers, used by Alembic.
revision = '537f6e20272f'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('media_type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path', name='unique_idx_path_upload')
    )
    op.create_table('employee_upload',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='fk_employee_id_employee_upload', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload.id'], name='fk_upload_id_employee_upload', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('employee_id', 'upload_id')
    )
    op.drop_table('apscheduler_jobs')
    op.add_column(u'employee', sa.Column('photo_upload_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_photo_upload_id_employee', 'employee', 'upload', ['photo_upload_id'], ['id'])
    op.drop_column(u'employee', 'photo')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'employee', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_photo_id_employee', 'employee', type_='foreignkey')
    op.drop_column(u'employee', 'photo_upload_id')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    op.drop_table('employee_upload')
    op.drop_table('upload')
    ### end Alembic commands ###
