"""alter db

Revision ID: 53f142d26c34
Revises: 3cc7cb081f5
Create Date: 2015-04-06 22:40:30.697758

"""

# revision identifiers, used by Alembic.
revision = '53f142d26c34'
down_revision = '3cc7cb081f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_item.id'], name='fk_order_item_id_general_service', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name='fk_resource_id_general_service', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('general_service')
    ### end Alembic commands ###
