"""alter db

Revision ID: 551c217291e2
Revises: 4c0445e408e1
Create Date: 2015-04-26 20:07:30.855119

"""

# revision identifiers, used by Alembic.
revision = '551c217291e2'
down_revision = '4c0445e408e1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.add_column('order_item', sa.Column('confirmation', sa.Boolean(), nullable=True))
    op.add_column('order_item', sa.Column('confirmation_date', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_item', 'confirmation_date')
    op.drop_column('order_item', 'confirmation')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    ### end Alembic commands ###
