"""alter db

Revision ID: 55bedab769b6
Revises: 39b91c3229bf
Create Date: 2014-09-14 19:36:28.783450

"""

# revision identifiers, used by Alembic.
revision = '55bedab769b6'
down_revision = '39b91c3229bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liability', sa.Column('descr', sa.String(length=255), nullable=True))
    op.drop_column('outgoing', 'invoice_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outgoing', sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('liability', 'descr')
    ### end Alembic commands ###
