"""alter db

Revision ID: 5725626e8733
Revises: 3d04ef2ed0fa
Create Date: 2014-04-19 21:25:10.303773

"""

# revision identifiers, used by Alembic.
revision = '5725626e8733'
down_revision = '3d04ef2ed0fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('closed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'closed')
    ### end Alembic commands ###
