"""alter db

Revision ID: 585291a3f82
Revises: 5a564ae775ef
Create Date: 2014-10-25 22:33:47.701677

"""

# revision identifiers, used by Alembic.
revision = '585291a3f82'
down_revision = '5a564ae775ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
