"""alter db

Revision ID: 5984ec75fe6f
Revises: d6019e611353
Create Date: 2016-05-09 11:48:51.032917

"""

# revision identifiers, used by Alembic.
revision = '5984ec75fe6f'
down_revision = 'd6019e611353'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
