"""alter db

Revision ID: 59a442cc5fdc
Revises: 4ae38fe41ca
Create Date: 2014-06-28 17:10:12.144655

"""

# revision identifiers, used by Alembic.
revision = '59a442cc5fdc'
down_revision = '4ae38fe41ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
