"""alter db

Revision ID: 59c1b648b2bb
Revises: 2039649e87df
Create Date: 2014-10-09 20:42:31.024367

"""

# revision identifiers, used by Alembic.
revision = '59c1b648b2bb'
down_revision = '2039649e87df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('descr', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name='fk_resource_id_note', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_resource',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], name='fk_note_id_note_resource', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name='fk_resource_id_note_resource', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('note_id', 'resource_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_resource')
    op.drop_table('note')
    ### end Alembic commands ###
