"""alter db

Revision ID: 5a3c381faf97
Revises: 43cdee2b7f13
Create Date: 2014-08-16 20:52:28.182091

"""

# revision identifiers, used by Alembic.
revision = '5a3c381faf97'
down_revision = '43cdee2b7f13'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
