"""alter db

Revision ID: 5a564ae775ef
Revises: 2a617e51627f
Create Date: 2014-10-25 22:31:40.399324

"""

# revision identifiers, used by Alembic.
revision = '5a564ae775ef'
down_revision = '2a617e51627f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
