"""alter db

Revision ID: 5e7cd4ddaa5
Revises: 2dfe833c5d29
Create Date: 2014-09-07 16:55:32.786570

"""

# revision identifiers, used by Alembic.
revision = '5e7cd4ddaa5'
down_revision = '2dfe833c5d29'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
