"""alter db

Revision ID: 735cec8a7bc0
Revises: d115817efcba
Create Date: 2016-09-17 19:02:18.585491

"""

# revision identifiers, used by Alembic.
revision = '735cec8a7bc0'
down_revision = 'd115817efcba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
