"""alter db

Revision ID: 768880891cd
Revises: 528bd115509c
Create Date: 2014-09-14 21:50:33.279113

"""

# revision identifiers, used by Alembic.
revision = '768880891cd'
down_revision = '528bd115509c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outgoing', 'account_item_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outgoing', sa.Column('account_item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
