"""alter db

Revision ID: 7fae44a4ebc
Revises: 3a4b3406bbdd
Create Date: 2014-04-15 20:51:27.627217

"""

# revision identifiers, used by Alembic.
revision = '7fae44a4ebc'
down_revision = '3a4b3406bbdd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('task_resource_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('reminder', sa.DateTime(), nullable=True),
    sa.Column('descr', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='fk_employee_id_task', onupdate='cascade', ondelete='cascade', use_alter=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name='fk_resource_id_task', onupdate='cascade', ondelete='cascade', use_alter=True),
    sa.ForeignKeyConstraint(['task_resource_id'], ['resource.id'], name='fk_task_resource_id_task', onupdate='cascade', ondelete='cascade', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    ### end Alembic commands ###
