"""alter db

Revision ID: 808944506f8
Revises: 36d1b5949680
Create Date: 2014-08-16 19:48:36.143457

"""

# revision identifiers, used by Alembic.
revision = '808944506f8'
down_revision = '36d1b5949680'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
