"""alter db

Revision ID: a921de174d7
Revises: 46613352f250
Create Date: 2014-04-28 18:20:18.130247

"""

# revision identifiers, used by Alembic.
revision = 'a921de174d7'
down_revision = '46613352f250'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('photo', sa.String(), nullable=True))
    op.drop_column('employee', 'attachment_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('attachment_id', sa.INTEGER(), nullable=True))
    op.drop_column('employee', 'photo')
    ### end Alembic commands ###
