"""alter db

Revision ID: b1eac8a9f577
Revises: 04f33a9d75b5
Create Date: 2016-08-15 20:23:54.003594

"""

# revision identifiers, used by Alembic.
revision = 'b1eac8a9f577'
down_revision = '04f33a9d75b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
