"""alter db

Revision ID: b841a3094e3
Revises: 447962be6863
Create Date: 2015-04-26 21:20:40.851992

"""

# revision identifiers, used by Alembic.
revision = 'b841a3094e3'
down_revision = '447962be6863'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_item', 'status',
               existing_type=sa.SMALLINT(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_item', 'status',
               existing_type=sa.SMALLINT(),
               nullable=True)
    ### end Alembic commands ###
