"""alter db

Revision ID: bdbc18f749f6
Revises: 1e661947fa33
Create Date: 2016-05-15 17:39:27.590882

"""

# revision identifiers, used by Alembic.
revision = 'bdbc18f749f6'
down_revision = '1e661947fa33'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'fk_employee_id_task', 'task', type_='foreignkey')
    op.drop_column('task', 'employee_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(u'fk_employee_id_task', 'task', 'employee', ['employee_id'], ['id'], onupdate=u'CASCADE', ondelete=u'RESTRICT')
    ### end Alembic commands ###
