"""alter db

Revision ID: c38723878dbe
Revises: d73a81056977
Create Date: 2016-09-18 10:11:21.955951

"""

# revision identifiers, used by Alembic.
revision = 'c38723878dbe'
down_revision = 'd73a81056977'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_subscription',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='fk_employee_id_employee_subscription', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name='fk_resource_id_employee_subscription', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('employee_id', 'resource_id')
    )
    op.drop_table('subscription_resource')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_resource',
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], [u'employee.id'], name=u'fk_employee_id_subscription_resource', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.ForeignKeyConstraint(['resource_id'], [u'resource.id'], name=u'fk_resource_id_subscription_resource', onupdate=u'CASCADE', ondelete=u'RESTRICT'),
    sa.PrimaryKeyConstraint('employee_id', 'resource_id', name=u'subscription_resource_pkey')
    )
    op.drop_table('employee_subscription')
    ### end Alembic commands ###
