"""alter db

Revision ID: cac2848ba45
Revises: None
Create Date: 2014-11-12 17:00:42.131971

"""

# revision identifiers, used by Alembic.
revision = 'cac2848ba45'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outgoing_transfer',
    sa.Column('outgoing_id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['outgoing_id'], ['outgoing.id'], name='fk_outgoing_id_outgoing_transfer', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer.id'], name='fk_transfer_id_outgoing_transfer', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('outgoing_id', 'transfer_id')
    )
    op.create_table('refund_transfer',
    sa.Column('refund_id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['refund_id'], ['refund.id'], name='fk_refund_id_refund_transfer', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer.id'], name='fk_transfer_id_refund_transfer', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('refund_id', 'transfer_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refund_transfer')
    op.drop_table('outgoing_transfer')
    ### end Alembic commands ###
