"""alter db

Revision ID: d115817efcba
Revises: db9e3d6db63c
Create Date: 2016-09-17 18:41:37.194039

"""

# revision identifiers, used by Alembic.
revision = 'd115817efcba'
down_revision = 'db9e3d6db63c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
