"""alter db

Revision ID: d73a81056977
Revises: 735cec8a7bc0
Create Date: 2016-09-18 10:09:09.364433

"""

# revision identifiers, used by Alembic.
revision = 'd73a81056977'
down_revision = '735cec8a7bc0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_resource',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='fk_employee_id_subscription_resource', onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name='fk_resource_id_subscription_resource', onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('employee_id', 'resource_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_resource')
    ### end Alembic commands ###
