"""alter db

Revision ID: d7b5e91f921
Revises: 3df3b48fc5e
Create Date: 2014-04-29 11:44:58.003230

"""

# revision identifiers, used by Alembic.
revision = 'd7b5e91f921'
down_revision = '3df3b48fc5e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour', sa.Column('advsource_id', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour', 'advsource_id')
    ### end Alembic commands ###
