"""alter db

Revision ID: dccf36ae49e4
Revises: 9d6e4f7a0f93
Create Date: 2016-08-15 20:41:54.200378

"""

# revision identifiers, used by Alembic.
revision = 'dccf36ae49e4'
down_revision = '9d6e4f7a0f93'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mail', 'html_content',
               existing_type=sa.TEXT(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mail', 'html_content',
               existing_type=sa.TEXT(),
               nullable=False)
    ### end Alembic commands ###
