"""alter db

Revision ID: deff2700efc6
Revises: d9b134d71b1f
Create Date: 2016-09-17 17:47:36.687810

"""

# revision identifiers, used by Alembic.
revision = 'deff2700efc6'
down_revision = 'd9b134d71b1f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'title')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
