"""alter db

Revision ID: e4fdb3f65a6
Revises: 3fc172ec8033
Create Date: 2014-04-28 10:10:04.095270

"""

# revision identifiers, used by Alembic.
revision = 'e4fdb3f65a6'
down_revision = '3fc172ec8033'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
