"""alter db

Revision ID: ef3412b067f
Revises: 542af389e25e
Create Date: 2015-04-25 22:05:24.201267

"""

# revision identifiers, used by Alembic.
revision = 'ef3412b067f'
down_revision = '542af389e25e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.add_column('tour', sa.Column('end_transport_id', sa.Integer(), nullable=False))
    op.add_column('tour', sa.Column('end_transport_info', sa.String(length=128), nullable=True))
    op.add_column('tour', sa.Column('start_transport_id', sa.Integer(), nullable=False))
    op.add_column('tour', sa.Column('start_transport_info', sa.String(length=128), nullable=True))
    op.add_column('tour', sa.Column('transfer_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_start_transport_id_tour', 'tour', 'transport', ['start_transport_id'], ['id'])
    op.create_foreign_key('fk_end_transport_id_tour', 'tour', 'transport', ['end_transport_id'], ['id'])
    op.create_foreign_key('fk_transfer_id_tour', 'tour', 'transfer', ['transfer_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transfer_id_tour', 'tour', type_='foreignkey')
    op.drop_constraint('fk_end_transport_id_tour', 'tour', type_='foreignkey')
    op.drop_constraint('fk_start_transport_id_tour', 'tour', type_='foreignkey')
    op.drop_column('tour', 'transfer_id')
    op.drop_column('tour', 'start_transport_info')
    op.drop_column('tour', 'start_transport_id')
    op.drop_column('tour', 'end_transport_info')
    op.drop_column('tour', 'end_transport_id')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    ### end Alembic commands ###
