"""alter db

Revision ID: f884312b3e4
Revises: 64457af6068
Create Date: 2015-06-13 15:25:29.083733

"""

# revision identifiers, used by Alembic.
revision = 'f884312b3e4'
down_revision = '64457af6068'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.add_column('income', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('income', sa.Column('sum', sa.Numeric(precision=16, scale=2), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('income', 'sum')
    op.drop_column('income', 'date')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    ### end Alembic commands ###
